### ISSUE TITLE
Updating for Ecto 3

### ISSUE THREAD

**Issue by lackac** [jumpn/ecto_replay_sandbox#2]
I've been using `ecto_replay_sandbox` with [redshift_ecto](https://github.com/100starlings/redshift_ecto) which I'm looking to update for Ecto 3. Since `ecto_replay_sandbox` is a dependency I started looking into updating it as well. I don't think it's going to be a simple process as much have changed in the underlying libraries (e.g. [db_connection changes](https://github.com/elixir-ecto/db_connection/issues/167)) so I would welcome any help or guidance.

**Comment by lackac** [comment]
As a first step I wanted to setup the development environment for the project in its current state. I have no experience with CockroachDB, but I managed to install it with Homebrew simply enough. However, when I try to run the tests I get the following errors:

```
❯ mix test
Compiling 1 file (.ex)
Generated ecto_replay_sandbox app

15:53:54.411 [error] GenServer #PID<0.255.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table): no data source matches prefix: t
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil

15:53:54.413 [error] GenServer #PID<0.262.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table): no data source matches prefix: t
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (MatchError) no match of right hand side value: {:error, "ERROR 42P01 (undefined_table): no data source matches prefix: t"}
    test/test_helper.exs:44: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
```

First I thought that I needed to create the database. That's not the case as it is automatically recreated in [test/test_helper.exs:43-44](https://github.com/jumpn/ecto_replay_sandbox/blob/6e7fc70df21f848c8a618bd3d56ce6234ed4b3ee/test/test_helper.exs#L43-L44). Next I suspected that there was an issue in `Ecto.Adapters.Postgres.storage_up/1` in that it's explicitly using `database: "postgres"` when connecting to the database which doesn't exist in CockroachDB. I realise that's not an issue as changing that to `"system"` didn't help.

What am I doing wrong?

**Comment by tlvenn** [comment]
Hi @lackac , I have just released a new version compatible with Ecto 3.x, enjoy ;)
